name: Build CoopAndreas

on:
  workflow_dispatch:

env:
  PLUGIN_SDK_DIR: ${{ github.workspace }}\plugin-sdk
  GTA_SA_DIR: ${{ github.workspace }}\gta_sa

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: Create Folders
      run: |
        mkdir gta_sa
        mkdir Release

    - name: Download and Build plugin-sdk
      run: |
        git clone https://github.com/DK22Pac/plugin-sdk.git
        cd plugin-sdk
        git checkout 050d18b6e1770477deab81a40028a40277583d97
        .\tools\premake\premake5.exe --file=tools\premake\premake5.lua vs2022
        msbuild plugin-sdk.sln /p:Configuration=Release /p:Platform=Win32 /m
      
    - name: Configure xmake
      run: xmake f -m release -a x86 -p windows -y

    - name: Build Proxy
      run: xmake --build proxy

    - name: Build Server
      run: xmake --build server

    - name: Build Client
      run: xmake --build client

    - name: Collect Release Files
      run: |
        Copy-Item -Path gta_sa\CoopAndreasSA.dll -Destination Release\CoopAndreasSA.dll
        Copy-Item -Path build\windows\x86\release\proxy.dll -Destination Release\eax.dll
        Copy-Item -Path build\windows\x86\release\server.exe -Destination Release\server.exe

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CoopAndreas-Ready-Files
        path: Release\*
